#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "${branch}" = "master" ]; then
  echo "Are you an idiot? committing directly to master branch is FORBIDDEN"
  exit 1
elif [ "${branch}" = "develop" ]; then 
  echo "Are you an idiot? committing directly to develop branch is FORBIDDEN"
  exit 1
fi
