on: [push]
jobs:
  to_gitlab:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://github.com/Gua-tk/Linux-Auto-Customizer'
            GIT_USERNAME: AleixMT
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
